output "secret_arn" {
  value = aws_secretsmanager_secret.db.arn
}

output "db_password" {
  description = "Ephemeral database password generated by AWS Secrets Manager"
  value       = ephemeral.aws_secretsmanager_random_password.db.random_password
  sensitive   = true
  ephemeral   = true
}